### PR TITLE
fix: Add new `flow.status` column to sync script

### PR DESCRIPTION
**Pull request by DafyddLlyr**
This PR adds the `flows.status` column to our sync script which was added in #3170 

Tested locally with `pnpm test-sync` command ✅

### CODE REVIEW

**Comment by RODO94** [comment]
@DafyddLlyr how significant are the check errors for Vultr? And how do I access the pizza?

**Comment by DafyddLlyr** [comment]
@RODO94 This PR is currently failing for the reasons outlined here - https://opensystemslab.slack.com/archives/C01E3AC0C03/p1716548233407109 (OSL Slack)

As this is holding you up from getting data locally you have a few options here - 
 - You could checkout this branch locally, sync data, then carry on working on your branch
 - You could `git cherry-pick` this commit into your branch, sync data, and carry on. When we merge / rebase your branch, this cherry picked commit will be removed by git as it will already be on the target branch 🍒

**Comment by jessicamcinchak** [comment]
@DafyddLlyr I've removed instance 3192 from vultr & fix is on `main`, so if you rebase to `main` here & push vultr should build fresh & succeed here for you on next go :crossed_fingers:

**Review by RODO94 — APPROVED** [review]
Tested locally and it runs fine, I can now see the database data.

**Pull request merged**
