### PR TITLE
feat: Use Hasura column presets to populate `creator_id`

### PR DESCRIPTION
**Pull request by RODO94**
This follows work on the demo workspace ticket: https://trello.com/c/EfaEQRzK/2441-create-a-demo-workspace

We found that the `creator_id` was not populating when we create a flow in the editor. To fix this, we decided to use Hasura Column Presets to reduce the number of places the change had to be made, and to make it more maintainable in the future.

We do sacrifice readability in the code base, but we found it was a better win for maintainability for a data field most people would expect to be populated by the user creating it. 

[Column Preset Docs](https://hasura.io/docs/2.0/auth/authorization/permissions/column-presets/)

### CODE REVIEW

**Comment by RODO94** [comment]
[Create a 'demo' workspace](https://trello.com/c/EfaEQRzK/2441-create-a-demo-workspace)

**Comment by DafyddLlyr** [comment]
@RODO94 Could you please also run E2E regression tests against this branch just to check that this method holds up with the mocking we've done there?

**Comment by RODO94** [comment]
@DafyddLlyr Regression tests have passed

**Review by DafyddLlyr — CHANGES_REQUESTED** [review]
Bit of a nitpick sorry, but there's no linting set up for this file afaik - it looks like it's your local IDE config that's changes from `"` to `'` here. 

Could you please change this back so that the only diff you've made for the column presets shows here?

**Review by DafyddLlyr — APPROVED** [review]
Nice! Thanks

**Pull request merged**
