### PR TITLE
feat: Submission Form added to General Settings

### PR DESCRIPTION
**Pull request by RODO94**
## What does this PR do?

This PR continues work in line with the Trello Ticket: https://trello.com/c/dVsTQpZZ/2984-allow-editors-to-see-update-their-teams-submission-email-in-team-settings-form

I have set up a **"Submission Information"** form in the **Team Settings** area. This comes with standard Formik wiring up with `ErrorWrapper` following patterns established in the other forms.

### CODE REVIEW

**Review by DafyddLlyr — COMMENTED** [review]
Code looks good, but the data sync on the pizza failed (so I can't log in to test!)

image

It can occasionally happen, it's not caused by a change in this PR. Two options to resolve this here - SSH onto Pizza and manually run script again, or just log into Vultr and destroy and recreate Pizza and associated DNS records for the PR.

I'm not sure if we've stepped through either of these processes yet. If you want to pair on either, or just try one out yourself, just let me know 👌

**Comment by RODO94** [comment]
Restart Vultr but still same thing so I have rebased on main and re run CI

**Review by DafyddLlyr — APPROVED** [review]
Perfect - nice and simple 👌

**Comment by RODO94** [comment]
[Allow editors to see/update their team's submission email in "Team settings" form](https://trello.com/c/dVsTQpZZ/2984-allow-editors-to-see-update-their-teams-submission-email-in-team-settings-form)

**Pull request merged**
