### PR TITLE
feat: GIS API returns granular Article 4 values for Doncaster

### PR DESCRIPTION
**Pull request by jessicamcinchak**
https://docs.google.com/spreadsheets/d/1W72w2oEii7OeAUBkP8ya9ipMxD3m-PNmmZPiusKAOfA/edit#gid=0

Example address that picks up `article4.doncaster.hmo` passport variable: 121 Thorne Rd, Doncaster DN2 5BQ

### CODE REVIEW

**Comment by jessicamcinchak** [comment]
[GIS API should return granular A4 passport variables for Doncaster](https://trello.com/c/jDLReSEe/2119-gis-api-should-return-granular-a4-passport-variables-for-doncaster)

**Comment by DafyddLlyr** [comment]
I'm having an issue with https://1174.planx.pizza/ - possibly a github action issue with build artefacts?

image

Could you try re-running the job maybe before we dive into troubleshooting?

**Comment by jessicamcinchak** [comment]
@DafyddLlyr thanks for taking an initial look. this is a strange one: regular re-run didn't change anything, so I destroyed the vultr instance and we'll see if it rebuilds correctly from scratch :crossed_fingers:

**Comment by jessicamcinchak** [comment]
closing this and re-opening to see if it clears up action build issue

**Pull request closed without merging**
