### PR TITLE
feat: Use Uniform Translator flow

### PR DESCRIPTION
**Pull request by DafyddLlyr**
## What does this PR do?
 - Removes Uniform application logic from the backend, in favour of the [Uniform Translator](https://editor.planx.uk/opensystemslab/uniform-translator) flow
 - I've made a few modifications to the flow (tested locally) - I'll get Alastair and/or George to also sign these changes off before we merge this

## Testing
 - Once the Pizza is up and changes to the Uniform Translator flow are manually copied across, I'll send a number of test applications across to Uniform staging environments in coordination with Kev to double check this works as expected

### CODE REVIEW

**Comment by jessicamcinchak** [comment]
[Improve test coverage for Uniform integration](https://trello.com/c/QwUs9nXs/2008-improve-test-coverage-for-uniform-integration)

**Comment by gunar** [comment]
[Use Uniform Translator instead of hard-coded values](https://trello.com/c/BJTQ1YZk/2025-use-uniform-translator-instead-of-hard-coded-values)

**Review by gunar — APPROVED** [review]
Code looks good. It's obviously a pity we can't type-check passport variables (which are in runtime) but I trust your judgment on the trade-offs of this solution. Approving here under the assumption that you'll be running those manual end-to-end tests as you've mentioned :+1:

**Comment by DafyddLlyr** [comment]
Tested by @Alastairparvin - Uniform translator content updated on prod, portal moved below "Declarations", and all flows published.

**Pull request merged**
