### PR TITLE
feat: Add section descriptions

### PR DESCRIPTION
**Pull request by ianjon3s**
### Summary

- PR adds the option to add a rich-text description to sections
- `<dl>` structure is maintained, I've checked and nesting a `<div>` inside a `<dl>` is valid HTML [source](https://html.spec.whatwg.org/multipage/grouping-content.html#the-dl-element)
- Tests and storybook updated accordingly

Related to Trello card:
https://trello.com/c/SGy6v0Sm/2587-investigate-section-descriptions

Example:
https://2240.planx.pizza/lambeth/apply-for-prior-approval/preview

### CODE REVIEW

**Review by DafyddLlyr — APPROVED** [review]
Looking great! 👍

**Comment by ianjon3s** [comment]
[[Investigate] section descriptions](https://trello.com/c/SGy6v0Sm/2587-investigate-section-descriptions)

**Comment by ianjon3s** [comment]
Thanks @DafyddLlyr !

**Comment by ianjon3s** [comment]
Merging this now and will apply any subsequent changes from PO feedback

**Pull request merged**
