### PR TITLE
feat: mobile styles update

### PR DESCRIPTION
**Pull request by ianjon3s**
### Summary

PR updates and fixes a number of mobile specific styles, following extensive mobile QA.

### Updates

- Updates default "factor" for responsive font resizing
- Adds small button size
- Adds missing `<Typography>` where needed
- Adjusts margins and padding of numerous components to unify layout
- Changes hierarchy of `<MapContainer>` and `<MapFooter>` to prevent overlap on smaller screens
- Adds a `nowrap` span to red line size indicator to keep units (m²) on same line as number

### Previews

Size comparison before (left) & after (right)

image

image

### CODE REVIEW

**Comment by DafyddLlyr** [comment]
Pizza link for mobile 👇 

frame

**Review by DafyddLlyr — CHANGES_REQUESTED** [review]
I'd suggest having a crack at converting the shared style in `fullWidthContent()` to it's own component - this will probably tidy a few things up and be a simpler way to understand structure and layout as we're building components I think.

**Review by DafyddLlyr — APPROVED** [review]
That's fantastic thanks - significant improvement to the readability of the code I think 👍

**Comment by ianjon3s** [comment]
Thanks @DafyddLlyr , agreed it makes a lot more sense as a component.

I've just got a couple more style updates coming through that I noticed on final run through the service/components.

**Pull request merged**
