### PR TITLE
fix: glitch in description button

### PR DESCRIPTION
**Pull request by gunar**
# Before

gif

# After

216468846-8c81debd-8292-4a40-84b4-ffd225a0627e

### CODE REVIEW

**Comment by gunar** [comment]
[Weird glitch on question with descriptions](https://trello.com/c/H9Tw81qI/2221-weird-glitch-on-question-with-descriptions)

**Comment by DafyddLlyr** [comment]
@gunar Is this ready for review?

**Comment by gunar** [comment]
@DafyddLlyr it wasn't before but it is now.

**Review by DafyddLlyr — APPROVED** [review]
Works a charm 👍

**Comment by gunar** [comment]
Added a dependency array to `useEffect` as it's a recommended practice to try and keep re-renders to minimum. Tested on the pizza and it's (still) working, so merging now.

**Pull request merged**
