### PR TITLE
feat: add tags to portals

### PR DESCRIPTION
**Pull request by RODO94**
Following previous templates groundwork, this PR adds the ability to add tags to portals

### CODE REVIEW

**Review by DafyddLlyr — APPROVED** [review]
Great!

**Review by DafyddLlyr — CHANGES_REQUESTED** [review]
Sorry just quickly checked the Pizza!

It would be good to sort the layout here - 
image

**Comment by RODO94** [comment]
> Sorry just quickly checked the Pizza!
> 
> It would be good to sort the layout here - image
> 
> I know these components aren't as well structured as others, but I think even just sorting out the margin here would be enough.

Yes, good catch! I did stash these, I'll put up a fix now.

**Review by DafyddLlyr — COMMENTED** [review]
Code changes and visual output looking good! I think there's just some tests that need to be updated here and then we're good to go.

**Comment by RODO94** [comment]
> Code changes and visual output looking good! I think there's just some tests that need to be updated here and then we're good to go.

Yeah, I did wonder why I stashed the UI changes... all good now

**Review by DafyddLlyr — APPROVED** [review]
Perfect - thanks for those changes!

**Pull request merged**
